# Generated by Django 5.0.6 on 2024-05-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
