# Generated by Django 5.0.6 on 2024-05-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_id_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='note',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
