# Generated by Django 5.0.6 on 2024-05-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
