# Generated by Django 5.0.6 on 2024-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='house_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='street_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
