# Generated by Django 5.0.6 on 2024-05-18 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_client_last_login_alter_dispense_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='request',
            name='note',
        ),
        migrations.RemoveField(
            model_name='request',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADM', 'Admin'), ('CLT', 'Client')], default='CLT', max_length=20),
        ),
        migrations.CreateModel(
            name='RequestHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=5000, null=True)),
                ('handled_on', models.DateTimeField(auto_now_add=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.request')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
