# Generated by Django 5.0.6 on 2024-05-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_username'),
        ('api', '0012_alter_user_username'),
    ]

    operations = [
    ]
