# Generated by Django 5.0.6 on 2024-05-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_requesthandle_note_request_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cashpower_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
