# Generated by Django 5.0.6 on 2024-05-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_request_cashpower_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
